'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');
const { spawn } = require('child_process');
const { startServer, tmpDir, PNG_1PX } = require('./helpers');
const { parseTranscript } = require('../hooks/lib/transcript');

const HOOKS = path.join(__dirname, '..', 'hooks');
const PROJECT_DIR = '/work/my-shop';

// Строки в формате транскрипта Claude Code (~/.claude/projects/<proj>/<session>.jsonl)
const base = { sessionId: 'sess-1', cwd: PROJECT_DIR, isSidechain: false };
const user = (content, extra = {}) => ({ ...base, type: 'user', message: { role: 'user', content }, ...extra });
const assistant = (content, extra = {}) => ({ ...base, type: 'assistant', message: { role: 'assistant', content }, ...extra });
const toolUse = (id, name, input) => ({ type: 'tool_use', id, name, input });
const toolResult = (id, isError = false) => user([{ type: 'tool_result', tool_use_id: id, content: isError ? 'Error: String not found' : 'ok', is_error: isError }]);

function writeTranscript(dir, lines, subagentLines) {
  const file = path.join(dir, 'sess-1.jsonl');
  fs.writeFileSync(file, lines.map((l) => JSON.stringify(l)).join('\n') + '\n');
  if (subagentLines) {
    const sub = path.join(dir, 'sess-1', 'subagents');
    fs.mkdirSync(sub, { recursive: true });
    fs.writeFileSync(path.join(sub, 'agent-a1.jsonl'), subagentLines.map((l) => JSON.stringify(l)).join('\n') + '\n');
  }
  return file;
}

const FULL_TRANSCRIPT = [
  { type: 'queue-operation', operation: 'enqueue', sessionId: 'sess-1', content: 'x' },
  user('Caveat: The messages below were generated by the user while running local commands. DO NOT respond...', { isMeta: true }),
  user('<command-name>/model</command-name>\n<command-message>model</command-message>\n<command-args></command-args>'),
  user('<local-command-stdout>Set model to Opus</local-command-stdout>'),
  { type: 'attachment', attachment: { type: 'date', date: '2026-09-24' } },
  user([{ type: 'text', text: '<system-reminder>служебное</system-reminder>\nДобавь корзину в магазин' }, { type: 'image', source: {} }]),
  assistant([{ type: 'thinking', thinking: '...' }]),
  assistant([{ type: 'text', text: 'Сейчас посмотрю код.' }, toolUse('t1', 'Read', { file_path: `${PROJECT_DIR}/src/app.js` })]),
  toolResult('t1'),
  assistant([toolUse('t2', 'Edit', { file_path: `${PROJECT_DIR}/src/app.js`, old_string: 'a', new_string: 'b' })]),
  toolResult('t2'),
  assistant([toolUse('t3', 'Write', { file_path: `${PROJECT_DIR}/src/cart.js`, content: '...' })]),
  toolResult('t3'),
  assistant([toolUse('t4', 'Edit', { file_path: `${PROJECT_DIR}/src/broken.js`, old_string: 'zz', new_string: 'b' })]),
  toolResult('t4', true),
  assistant([toolUse('t5', 'MultiEdit', { file_path: `${PROJECT_DIR}/src/app.js`, edits: [] })]),
  toolResult('t5'),
  assistant([toolUse('t6', 'NotebookEdit', { notebook_path: `${PROJECT_DIR}/nb/analysis.ipynb`, new_source: '' })]),
  toolResult('t6'),
  assistant([toolUse('t7', 'Write', { file_path: '/etc/hosts-copy', content: '' })]),
  toolResult('t7'),
  user('И ещё поправь стили'),
  assistant([{ type: 'text', text: 'Готово: добавил корзину (src/cart.js) и подключил её в src/app.js.' }]),
  { type: 'last-prompt', lastPrompt: 'И ещё поправь стили' },
];
const SUBAGENT_TRANSCRIPT = [
  user('Задание сабагента', { isSidechain: true }),
  assistant([toolUse('s1', 'Edit', { file_path: `${PROJECT_DIR}/src/styles.css` })], { isSidechain: true }),
  toolResult('s1'),
  assistant([{ type: 'text', text: 'ответ сабагента — не итог сессии' }], { isSidechain: true }),
];

test('parseTranscript: первый запрос, успешные правки, последний ответ, сабагенты', () => {
  const dir = tmpDir();
  const file = writeTranscript(dir, FULL_TRANSCRIPT, SUBAGENT_TRANSCRIPT);
  const r = parseTranscript(file, { projectDir: PROJECT_DIR });
  assert.equal(r.task, 'Добавь корзину в магазин');
  assert.equal(r.summary, 'Готово: добавил корзину (src/cart.js) и подключил её в src/app.js.');
  assert.deepEqual(r.files, ['src/app.js', 'src/cart.js', 'nb/analysis.ipynb', '/etc/hosts-copy', 'src/styles.css']);
  fs.rmSync(dir, { recursive: true, force: true });
});

test('parseTranscript: слэш-команда с аргументами считается запросом, без аргументов — только запасной вариант', () => {
  const dir = tmpDir();
  let file = writeTranscript(dir, [
    user('<command-message>review</command-message>\n<command-name>/review</command-name>\n<command-args>проверь PR 12</command-args>'),
  ]);
  assert.equal(parseTranscript(file).task, '/review проверь PR 12');

  file = writeTranscript(dir, [user('<command-name>/init</command-name>\n<command-args></command-args>')]);
  assert.equal(parseTranscript(file).task, '/init');

  file = writeTranscript(dir, [
    user('<command-name>/clear</command-name>\n<command-args></command-args>'),
    user('Настоящий запрос'),
  ]);
  assert.equal(parseTranscript(file).task, 'Настоящий запрос');
  fs.rmSync(dir, { recursive: true, force: true });
});

test('parseTranscript: несуществующий файл и мусорные строки не роняют разбор', () => {
  assert.deepEqual(parseTranscript('/nope/none.jsonl'), { task: '', summary: '', files: [] });
  const dir = tmpDir();
  const file = path.join(dir, 's.jsonl');
  fs.writeFileSync(file, '{"type":"user","message":{"role":"user","content":"ок"}}\n{битая строка\n');
  assert.equal(parseTranscript(file).task, 'ок');
  fs.rmSync(dir, { recursive: true, force: true });
});

// Асинхронно: сервер дашборда живёт в этом же процессе, spawnSync заблокировал бы его
function runHook(script, input, env) {
  return new Promise((resolve, reject) => {
    const child = spawn(process.execPath, [path.join(HOOKS, script)], {
      env: { ...process.env, CLAUDE_PROJECT_DIR: '', ...env },
      stdio: ['pipe', 'pipe', 'pipe'],
    });
    let stdout = '';
    let stderr = '';
    child.stdout.on('data', (d) => { stdout += d; });
    child.stderr.on('data', (d) => { stderr += d; });
    child.on('error', reject);
    child.on('close', (status) => resolve({ status, stdout, stderr }));
    child.stdin.end(typeof input === 'string' ? input : JSON.stringify(input));
  });
}

test('session-end.js отправляет задачу в дашборд, повторный запуск обновляет ту же запись', async () => {
  const srv = await startServer();
  const dir = tmpDir();
  const transcript = writeTranscript(dir, FULL_TRANSCRIPT);
  const input = { session_id: 'sess-1', transcript_path: transcript, cwd: `${PROJECT_DIR}/src`, hook_event_name: 'SessionEnd', reason: 'other' };
  const env = { AGENT_DASHBOARD_URL: srv.base, AGENT_DASHBOARD_HOOK_SYNC: '1', CLAUDE_PROJECT_DIR: PROJECT_DIR };
  try {
    let r = await runHook('session-end.js', input, env);
    assert.equal(r.status, 0);
    assert.equal(r.stdout, '');
    let tasks = await (await fetch(`${srv.base}/api/tasks?project=my-shop`)).json();
    assert.equal(tasks.length, 1, 'проект = папка CLAUDE_PROJECT_DIR, а не текущий cwd (src)');
    assert.equal(tasks[0].task, 'Добавь корзину в магазин');
    assert.equal(tasks[0].source, 'hook');
    assert.equal(tasks[0].session_id, 'sess-1');
    assert.ok(tasks[0].files.includes('src/cart.js'));

    r = await runHook('session-end.js', input, env);
    assert.equal(r.status, 0);
    tasks = await (await fetch(`${srv.base}/api/tasks?project=my-shop`)).json();
    assert.equal(tasks.length, 1, 'без дублей');

    // без CLAUDE_PROJECT_DIR проект берётся из cwd
    r = await runHook('session-end.js', { ...input, session_id: 'sess-2', cwd: '/work/other-proj' }, { ...env, CLAUDE_PROJECT_DIR: '' });
    tasks = await (await fetch(`${srv.base}/api/tasks?project=other-proj`)).json();
    assert.equal(tasks.length, 1);
  } finally {
    await srv.stop();
    fs.rmSync(dir, { recursive: true, force: true });
  }
});

test('session-end.js в фоновом режиме: хук завершается сразу, задача приходит чуть позже', async () => {
  const srv = await startServer();
  const dir = tmpDir();
  const transcript = writeTranscript(dir, FULL_TRANSCRIPT);
  try {
    const started = Date.now();
    const r = await runHook('session-end.js', { session_id: 'bg-1', transcript_path: transcript, cwd: PROJECT_DIR }, { AGENT_DASHBOARD_URL: srv.base });
    const elapsed = Date.now() - started;
    assert.equal(r.status, 0);
    assert.ok(elapsed < 1000, `хук должен выходить быстро, а занял ${elapsed} мс`);
    let tasks = [];
    for (let i = 0; i < 40 && !tasks.length; i++) {
      await new Promise((res) => setTimeout(res, 100));
      tasks = await (await fetch(`${srv.base}/api/tasks?project=my-shop`)).json();
    }
    assert.equal(tasks.length, 1);
    assert.equal(tasks[0].session_id, 'bg-1');
  } finally {
    await srv.stop();
    fs.rmSync(dir, { recursive: true, force: true });
  }
});

test('session-end.js: сервер не запущен — молча выходит с кодом 0', async () => {
  const dir = tmpDir();
  const transcript = writeTranscript(dir, FULL_TRANSCRIPT);
  const r = await runHook('session-end.js', { session_id: 'x', transcript_path: transcript, cwd: PROJECT_DIR },
    { AGENT_DASHBOARD_URL: 'http://127.0.0.1:9', AGENT_DASHBOARD_HOOK_SYNC: '1' });
  assert.equal(r.status, 0);
  assert.equal(r.stdout, '');
  assert.equal(r.stderr, '');
  // мусор на stdin тоже не ошибка
  const r2 = await runHook('session-end.js', 'not json', {});
  assert.equal(r2.status, 0);
  fs.rmSync(dir, { recursive: true, force: true });
});

test('session-start.js печатает открытые правки проекта со скриншотами и session_id', async () => {
  const srv = await startServer();
  try {
    const fd = new FormData();
    fd.append('project', 'my-shop');
    fd.append('text', 'Кнопка «Купить» уезжает на мобильных');
    fd.append('images', new Blob([PNG_1PX], { type: 'image/png' }), 'a.png');
    const note = await (await fetch(`${srv.base}/api/notes`, { method: 'POST', body: fd })).json();
    const later = await (await fetch(`${srv.base}/api/notes`, {
      method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ project: 'my-shop', text: 'Вторая правка' }),
    })).json();
    const done = await (await fetch(`${srv.base}/api/notes`, {
      method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ project: 'my-shop', text: 'Уже сделано' }),
    })).json();
    await fetch(`${srv.base}/api/notes/${done.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: '{"status":"done"}' });
    await fetch(`${srv.base}/api/notes`, {
      method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ project: 'other', text: 'Не наша правка' }),
    });

    const r = await runHook('session-start.js', { session_id: 'sess-9', cwd: PROJECT_DIR, hook_event_name: 'SessionStart', source: 'startup' }, { AGENT_DASHBOARD_URL: srv.base });
    assert.equal(r.status, 0);
    const out = r.stdout;
    assert.match(out, /Проект в дашборде: «my-shop», session_id этой сессии: sess-9/);
    assert.match(out, new RegExp(`Правка #${note.id} .*:\\n   Кнопка «Купить» уезжает на мобильных`));
    assert.ok(out.includes(note.image_files[0]), 'абсолютный путь к скриншоту');
    assert.ok(out.indexOf(`#${note.id}`) < out.indexOf(`#${later.id}`), 'от старых к новым');
    assert.ok(!out.includes('Уже сделано'));
    assert.ok(!out.includes('Не наша правка'));
    assert.match(out, /PATCH .*\/api\/notes\/<id>/);

    const empty = await runHook('session-start.js', { session_id: 's', cwd: '/work/clean' }, { AGENT_DASHBOARD_URL: srv.base });
    assert.match(empty.stdout, /Открытых правок от пользователя для этого проекта нет/);
  } finally {
    await srv.stop();
  }
});

test('session-start.js: сервер не запущен — пустой вывод, код 0, быстро', async () => {
  const started = Date.now();
  const r = await runHook('session-start.js', { session_id: 's', cwd: PROJECT_DIR }, { AGENT_DASHBOARD_URL: 'http://127.0.0.1:9' });
  assert.equal(r.status, 0);
  assert.equal(r.stdout, '');
  assert.ok(Date.now() - started < 3000);
});

test('хук без stdin (ручной запуск) не зависает', async () => {
  const child = spawn(process.execPath, [path.join(HOOKS, 'session-start.js')], {
    env: { ...process.env, AGENT_DASHBOARD_URL: 'http://127.0.0.1:9' },
    stdio: ['pipe', 'pipe', 'pipe'],
  });
  // stdin открыт, но ничего не приходит
  const code = await new Promise((resolve) => child.on('exit', resolve));
  assert.equal(code, 0);
});
